### ISSUE TITLE
GuzzleHttp\Psr7\

### ISSUE THREAD

**Issue by JulianParge** [xdan/jodit-connectors#2]
There doesn't seem to be any mention of prerequisites anywhere, documentation is really poor, Jodit has a lot of potential, the editor works well and looks good but the file browser doesn't work at all and after installing connector, I'm greeted with `require_once 'vendor/autoload.php';` doesn't exist on index.php, hide that line and I'm getting errors about GuzzleHttp\Psr7 not being a function...

**Comment by xdan** [comment]
Thank you. I added link to full archive in README https://github.com/xdan/jodit-connectors
