### ISSUE TITLE
FileBrowser does not work with version 3.6.x

### ISSUE THREAD

**Issue by saosangmo** [xdan/jodit-connectors#20]
I use version 3.6.x, the PHP Connector have something wrong. Filebrowse can not open folders and files.
```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jodit/3.6.1/jodit.min.css"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/jodit/3.6.1/jodit.min.js"></script>
```
I have downgraded to ver. 3.5.1, everything work well.

**Comment by dfreerksen** [comment]
I just ran in to the same issue. The expected JSON response format has changed a little. That was unexpected from a minor release version. 

The tests give you an example of what the responses should look like https://github.com/xdan/jodit/blob/master/test/bootstrap.js#L165

**Comment by saosangmo** [comment]
This issue may be caused by Composer. I dont use Composer for my project, so this is dirty hack:
1. Open connect/Application.php
2. After line: `use Jodit\Application;` insert the code:
`include_once('/Applications/XAMPP/htdocs/sp/assets/connector/vendor/abeautifulsite/simpleimage/src/claviska/SimpleImage.php');
`
3. Replace`/Applications/XAMPP/htdocs/sp/assets` with your real path.

**Comment by artcd** [comment]
jodit v. 3.5.1

Error when deleting a file:
<img src="https://i.ibb.co/87fPSrv/Untitled-1.png">
