### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Tisoy21** [xdan/jodit-connectors#8]
Cannot convert undefined or null to object

how can i debug this 

![Screen Shot 2019-03-12 at 6 00 51 AM](https://user-images.githubusercontent.com/44186119/54161228-7a54d180-448c-11e9-9d1d-92b110f1d406.png)

**Comment by webdreamsCH** [comment]
Since i have installed PHP 8.0 i have the same issue, under 7.4 Vers. 3.0.32 works well. What is the problem ?
